language: python

python:
  - "2.6"
  - "2.7"

install: "pip install -r requirements.py"

script: nosetests

notifications:
  email:
    recipients:
      - apisupport@odesk.com
    on_failure: change
